### ISSUE TITLE
on pressing left it should rotate cat to 180deg feature

### ISSUE THREAD

**Issue by draceel07** [draceel07/move-a-cat#2]
on pressing left it should rotate cat to 180deg if any one can add this feature

**Comment by Himanshuxyzz** [comment]
hey i can fix this issue can uh please assign this to me it will help me

**Comment by draceel07** [comment]
> 
> 
> hey i can fix this issue can uh please assign this to me it will help me

yeah sure go on

**Comment by draceel07** [comment]
> 
> 
> hey i can fix this issue can uh please assign this to me it will help me
i would be great help if u fix all these issues
